name: AndroidBuild

on:
  pull_request :
    branches : [ master ]
  push :
    branches : [ master ]

jobs:
  test-feature:
    runs-on: macOS-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests with Gradle
        run: ./gradlew test